//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2.CONTEXT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STUDENT_TBL
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Can't Left Blank !")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Can't Left Blank !")]
        public string FNAME { get; set; }
        [Required(ErrorMessage = "Can't Left Blank !")]
        [EmailAddress]
        public string EMAIL { get; set; }
        [Required(ErrorMessage = "Can't Left Blank !")]
        [MinLength(8,ErrorMessage ="Must be Min. 8 digit.")]
        public string MOBILE { get; set; }
        [Required(ErrorMessage = "Can't Left Blank !")]
        public string DESCRIPTION { get; set; }

        public STUDENT_TBL()
        {
            ID = 0;
            NAME = "";
            FNAME = "";

        }
    }
}
